version: "3"

services:

  signaling-redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  signaling:
    image: denoland/deno:alpine-1.39.4
    restart: always
    depends_on:
      - signaling-redis
    environment:
      # If "on" is logging, otherwise is not. In production, set it to "off".
      SIGNALING_LOGGING: ${SIGNALING_LOGGING:-on}
      # In production, change it to suit the environment.
      SIGNALING_CORS_ORIGIN: ${SIGNALING_CORS_ORIGIN:-*}
    ports:
      - 3010:3000
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["deno", "run", "--allow-env", "--allow-net", "index.ts"]
