version: "3"

services:

  signaling:
    image: denoland/deno:alpine-1.39.4
    restart: always
    environment:
      # If "on" is logging, otherwise is not. In production, set it to "off".
      SIGNALING_LOGGING: ${SIGNALING_LOGGING:-on}
      # In production, change it to suit the environment.
      SIGNALING_CORS_ORIGIN: ${SIGNALING_CORS_ORIGIN:-*}
      # In production, change it to suit the environment.
      SIGNALING_CORS_CREDENTIALS: ${SIGNALING_CORS_CREDENTIALS:-false}
    ports:
      - 3010:3000
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["deno", "run", "--allow-env", "--allow-net", "index.ts"]
